name: Upstream Workflow

permissions:
  actions: write
  contents: read


on:
  workflow_dispatch:
    inputs:
      tag1:
        description: "Tag for upstream test run"
        required: true
        type: string

jobs:
  run-upstream-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Cucumber Tests (TAG1)
        run: |
          echo "Running with TAG1: ${{ inputs.tag1 }}"
          mvn test -Dcucumber.filter.tags="${{ inputs.tag1 }}"

      - name: Trigger Downstream Workflow
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "downstream.yml",
              ref: "master",
              inputs: {
                tag2: "@Subtract"
              }
            })

      - name: Done
        run: echo "Downstream workflow triggered."
